services:
  postgres:
    container_name: postgres_todo
    image: 'postgres:15-alpine'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      TZ: UTC
      PGTZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d/
    restart: unless-stopped

volumes:
  minio_data:
  postgres_data: